minichua/site/apis/urls.py
from django.urls import path

from . import views

app_name = 'mini_api'

urlpatterns = [
    path('', views.ListMinichua.as_view(), name='home'),
    path('<int:pk>/', views.DetailMinichua.as_view(), name='mini'),
    path('tag/', views.ListTags.as_view(), name='tags'),
    path('tag/<int:pk>', views.DetailTags.as_view()),
    path('signup/', views.SignupView.as_view(), name='signup'),
    # path('all/', views.ListMinichua.as_view(), name='all'),
    ]

minichua/site/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('apis/v1/', include('apis.urls')),
    path('user/', include('django.contrib.auth.urls'), name='login'),
    path('user/', include('apis.urls')),
    path('', include('minichua.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

minichua/site/minichua/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'minichua'
urlpatterns = [
    path('', TemplateView.as_view(template_name="index.html"), name='home'),
]

minichua/site/apis/models.py
from django.db import models

# Create your models here.

minichua/site/minichua/models.py
from django.db import models

class Mini(models.Model):
    name = models.CharField(max_length=200)
    image_url = models.CharField(max_length=600)
    tags = models.ManyToManyField('Tags', blank=True)
    url = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Tags(models.Model):
    tag = models.CharField(max_length=200)

    def __str__(self):
        return self.tag

minichua/site/apis/views.py
from django.shortcuts import render
from rest_framework import generics
from config.pagination import CustomPagination

from django.views import generic
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy

from minichua import models
from .serialzers import MiniSerializer, TagsSerializer

class ListMinichua(generics.ListCreateAPIView):
    queryset = models.Mini.objects.all()
    serializer_class = MiniSerializer
    pagination_class = CustomPagination
    filterset_fields = ['tags','tags__tag']

class DetailMinichua(generics.RetrieveUpdateDestroyAPIView):
    queryset = models.Mini.objects.all()
    serializer_class = MiniSerializer
    template_name = 'detail.html'
    filterset_fields = ['tags', 'tags__tag']

class ListTags(generics.ListCreateAPIView):
    queryset = models.Tags.objects.all()
    serializer_class = TagsSerializer

class DetailTags(generics.RetrieveUpdateDestroyAPIView):
    queryset = models.Tags.objects.all()
    serializer_class = TagsSerializer

class SignupView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

class UserProfileView(generic.DetailView):
    model = User
    template_name = 'user_profile.html'

    def get_object(self):
        return get_object_or_404(User, username=self.kwargs['username'])

minichua/site/minichua/views.py
from django.shortcuts import render

# Create your views here.

minichua/site/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
    <title>Minichua: Miniature Model Finder</title>
</head>
<body>
    <header>
        <div class="nav-left">
            <h1><a href="{% url 'minichua:home' %}">Minichua</a></h1>
        </div>
        <div class="nav-right">
            {% if request.user.is_authenticated %}
                <p><a href="{% url 'logout' %}">Logout</a></p>
            {% else %}
                <a href="{% url 'login' %}">Login</a></p>
                <a href="{% url 'mini_api:signup'%}">Sign Up</a></p>
            {% endif %}
        </div>
    </header>
    <div class="container">
        {% block content %}
        {% endblock content%}
    </div>
</body>
</html>

minichua/site/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <div id="app">
        <h1>Mini Finder</h1> 
        <label for='tag'>Filter by tag:</label>
        <select @change='tagSelect($event)' name='tag' id='tag' v-model='key'>
            <option>-</option>
            <option v-for='word in tag_options' v-bind:value='word.id'>[[ word.tag ]]</option>
        </select>
        <input type='text' @keyup.enter='searchMinis' name='tag' v-model='search'>
        <button style='border-color: black' class="btn btn-default" @click='searchMinis'>Search</button>
        <button style='border-color: black' class="btn btn-default" @click='showAll' name='all'>Browse All</button>
        <ul class='container'>
            <div class='row'>
                <li v-for='mini in minis.results' class ='col-md-6'>
                    <p>[[ mini.name ]]</p>
                    <div v-if='mini.displayDetail != true'>
                        <button style='border-color: black' class="btn btn-default" @click='mini.displayDetail = true'>Show</button>
                    </div>
                    <br>
                    <img v-if='mini.displayDetail != true' class='img-thumbnail' :src='mini.image_url[0]'>
                    <div v-if='mini.displayDetail'>
                        <button style='border-color: black' class="btn btn-default" @click='mini.displayDetail = false'>Hide</button>
                        <img class='col-md-1, img-thumbnail' v-for='img in mini.image_url' :src='img'>
                        <a :href='mini.url'>[[ mini.name ]]'s page</a>

                        <div class='container'>
                            <div class ='row'>
                                <div id='taglist'  v-for='tag in mini.tag_names'>[[ tag ]]</div>
                            </div>
                        </div>
                        <input type='text' v-model='new_tag' @keyup.enter='pushTag(mini)'>
                        <button style='border-color: black' class="btn btn-default" @click='pushTag(mini)'>Add Tag</button>
                    </div> 
                </li>
            </div>
        </ul>
        <template v-if='minis.results'>
            <template v-if='method === "filter"'>    
                <button v-if='page != 1' @click='firstPageFilter()' type='button'>First Page</button>
                <button v-if="page > 1" @click='previousPageFilter()' type='button'>Previous Page</button>
                <button v-if='minis.next' @click='nextPageFilter($event)' type='button'>Next Page</button>
            </template>
            <template v-if='method === "search"'>    
                <button v-if='page != 1' @click='firstPageSearch()' type='button'>First Page</button>
                <button v-if="page > 1" @click='previousPageSearch()' type='button'>Previous Page</button>
                <button v-if='minis.next' @click='nextPageSearch($event)' type='button'>Next Page</button>
            </template>   
            <template v-if='method === "all"'>    
                <button v-if='page != 1' @click='firstPageAll()' type='button'>First Page</button>
                <button v-if="page > 1" @click='previousPageAll()' type='button'>Previous Page</button>
                <button v-if='minis.next' @click='nextPageAll($event)' type='button'>Next Page</button>
            </template>          
        </template>
    </div>
    
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script src="https://unpkg.com/vue"></script>
    <script>
        new Vue({
            el: '#app',
            data: {
                baseURL: 'http://localhost:8000/apis/v1/?page=',
                minis: [],
                key: '',
                tag_options: '',
                minitag: [],
                page: 1,
                new_tag: '',
                search: '',
                method: '',
                error_message: false,
                exists: null,
                tag_exists: null,
                relation_exists: null,
                index_check: '',
            },
            delimiters: [
                '[[',']]'
            ],
            methods: {
                createTag: function(mini){
                    axios({
                        url: 'http://localhost:8000/apis/v1/tag/',
                        method: 'post',
                        data: {
                                tag: this.new_tag,
                                mini_set: [mini.id]
                        }
                    })
                },
                addTag: function(mini){
                    axios({
                        url: 'http://localhost:8000/apis/v1/tag/',
                        method: 'patch',
                        data: {
                                mini_set: [mini.id]
                        }
                    })
                },
                pushTag: function(mini){
                    this.checkTag(mini)
                    if (!this.tag_exists) {
                        this.createTag(mini)
                    }
                    // else if (!this.relation_exists) {
                        
                    //     this.addTag(mini)
                    // }
                },
                checkTag: function(mini) {
                    this.tag_exists = false
                    this.relation_exists = false
                    this.tag_options.map(name => {
                        if (name.tag === this.new_tag) {
                            this.tag_exists = true
                        }
                    mini.tag_names.map(tag => {
                        if (tag.tag_names === this.new_tag) {
                            this.relation_exists = true
                            this.index_check = tag.find_index(index => (index === tag))
                        }
                    })
                    })
                },
                filterMinis : function () {
                    axios({
                        url: this.baseURL+this.page,
                        method: 'get',
                        params: {
                            tags : this.key,
                            page: this.page
                        }
                    }).then (response => {
                        const manipulatedData = response.data
                        manipulatedData.results = manipulatedData.results.map(mini => {
                            mini.displayDetail = false
                            return mini
                        })
                        manipulatedData.results = manipulatedData.results.map(mini => {
                            mini.image_url = mini.image_url.slice(2,-2).split("', '")
                            return mini
                        })
                        manipulatedData.results = manipulatedData.results.map(mini => {
                            mini.tag_names = []
                            mini.tags.forEach(mini_tag => {
                                let tag = this.tag_options.find(tag => {
                                    return tag.id === mini_tag
                                })
                                mini.tag_names.push(tag.tag)
                                tag_names = this.minitag
                            });
                            return mini
                        })
                        this.minis = manipulatedData
                        this.method = 'filter'
                        this.search = ''
                    })
                },
                searchMinis : function () {
                    axios({
                        url: this.baseURL+this.page,
                        method: 'get',
                        params: {
                            tags__tag: this.search,
                            page: this.page
                        }
                    }).then (response => {
                        const manipulatedData = response.data
                        manipulatedData.results = manipulatedData.results.map(mini => {
                            mini.displayDetail = false
                            return mini
                        })
                        manipulatedData.results = manipulatedData.results.map(mini => {
                            mini.image_url = mini.image_url.slice(2,-2).split("', '")
                            return mini
                        })
                        manipulatedData.results = manipulatedData.results.map(mini => {
                            mini.tag_names = []
                            mini.tags.forEach(mini_tag => {
                                let tag = this.tag_options.find(tag => {
                                    return tag.id === mini_tag
                                })
                                mini.tag_names.push(tag.tag)
                            });
                            return mini
                        })
                        this.minis = manipulatedData
                        this.method = 'search'
                        this.key = ''
                    })
                },
                showAll : function () {
                    axios({
                        url: this.baseURL+this.page,
                        method: 'get',
                        params: {
                        }
                    }).then (response => {
                        const manipulatedData = response.data
                        manipulatedData.results = manipulatedData.results.map(mini => {
                            mini.displayDetail = false
                            return mini
                        })
                        manipulatedData.results = manipulatedData.results.map(mini => {
                            mini.image_url = mini.image_url.slice(2,-2).split("', '")
                            return mini
                        })
                        manipulatedData.results = manipulatedData.results.map(mini => {
                            mini.tag_names = []
                            mini.tags.forEach(mini_tag => {
                                let tag = this.tag_options.find(tag => {
                                    return tag.id === mini_tag
                                })
                                mini.tag_names.push(tag.tag)
                            });
                            return mini
                        })
                        this.minis = manipulatedData
                        this.method = 'all'
                        this.key = ''
                        this.search = ''
                    })
                },
                tagSelect(event){
                    this.page = 1
                    this.filterMinis()
                },
                firstPageFilter: function () {
                    this.page = 1,
                    this.filterMinis()
                },
                nextPageFilter: function (event) {
                    this.page += 1,
                    this.filterMinis()
                },
                previousPageFilter: function () {
                    this.page -= 1,
                    this.filterMinis()
                },
                firstPageSearch: function () {
                    this.page = 1,
                    this.searchMinis()
                },
                nextPageSearch: function (event) {
                    this.page += 1,
                    this.searchMinis()
                },
                previousPageSearch: function () {
                    this.page -= 1,
                    this.searchMinis()
                },
                firstPageAll: function () {
                    this.page = 1,
                    this.showAll()
                },
                nextPageAll: function (event) {
                    this.page += 1,
                    this.showAll()
                },
                previousPageAll: function () {
                    this.page -= 1,
                    this.showAll()
                },
                showDetail: function (event) {
                    this.displayDetail = true
                },
                hideDetail: function () {
                    this.displayDetail = false
                }
            },
            mounted: function() {
                axios({
                    url: 'http://localhost:8000/apis/v1/tag/',
                    method: 'get',
                }).then (response => {
                    this.tag_options = response.data
                })
            }
        })
    </script>
{% endblock content %}










                {% comment %} // pushTag: function(mini){
                //     this.checkTag()
                //     if (!this.exists) {
                //         this.createTag(mini)
                //     }
                // },
                // checkTag: function() {
                //     this.exists = false
                //     this.tag_options.map(name => {
                //         if (name.tag === this.new_tag) {
                //             this.exists = true
                //         } 
                //     })
                // }, {% endcomment %}

minichua/site/templates/signup.html
{% extends 'base.html' %}

{% block content %}

    <h1>Signup for Minichua</h1>
    <form action='' method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <input type='submit' value='Signup!'>
    </form>

{% endblock content%}
    